package ose.bionix.cn2.skullftp_gui.UI;

import ose.bionix.cn2.skullftp_gui.NetHandler;

/**
 * THIS FILE IS PARTIALLY AUTO-GENERATED BY APACHE NETBEANS IDE.
 * Alongside my primary IDE for this project, VSCode (with AI features turned off), I also used
 * NetBeans' Form Editor to quickly formulate the interface by dragging and dropping elements,
 * since manually positioning every element for it would be a massive chore.
 * The Form Editor (WHICH IS NOT AN AI) generate these codes on the fly as you make changes to
 * the form, and it expects them to not be modified AT ALL, or the editor will simply stop
 * functioning the next time you open the file.
 * As such, I did not change any bits of it throughout the development process, and therefore
 * when grading, you can skip the section that I have marked as generated by the IDE.
 * 
 * Thank you for understanding.
 */
public class Auth extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Auth.class.getName());
    private Main UImain;
    private NetHandler net;

    /**
     * Creates new form Auth
     */
    public Auth() {
        initComponents();
    }
    public Auth(Main UImain, NetHandler net) {
        this.UImain = UImain;
        this.net = net;
        initComponents();
        initListeners();
    }

    private void initListeners() {
        // "Anonymous" checkbox (grays out cred fields when checked)
        chkboxAsAnon.addActionListener(e -> {
            boolean isAnon = chkboxAsAnon.isSelected();
            fieldUser.setEnabled(!isAnon);
            fieldPassword.setEnabled(!isAnon);
        });
        // Login button
        buttonLogin.addActionListener(e -> {
            String user = chkboxAsAnon.isSelected() ? "anonymous" : fieldUser.getText();
            String pass = chkboxAsAnon.isSelected() ? "anon@ftp.net" : new String(fieldPassword.getPassword());
            // Dispatch a thread to attempt login to avoid freezing the GUI
            new Thread(() -> {
                try {
                    net.login(user, pass); 
                    // Load UI.Main once login successfully
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        UImain.onAuth(); 
                        this.dispose();
                    });
                } catch (Exception ex) {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        javax.swing.JOptionPane.showMessageDialog(this, "Authentication failure: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    });
                }
            }).start();
        });
    }

    // ===== BEGIN NETBEANS GENERATED CODE =====

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldUser = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        chkboxAsAnon = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fieldPassword.setToolTipText("");

        buttonLogin.setText("Login");

        chkboxAsAnon.setText("Anonymous login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldUser)
                    .addComponent(fieldPassword)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkboxAsAnon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(buttonLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(chkboxAsAnon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Auth().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JCheckBox chkboxAsAnon;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUser;
    // End of variables declaration//GEN-END:variables

    // ===== END NETBEANS GENERATED CODE =====
}
