package ose.bionix.cn2.skullftp_gui.UI;

import ose.bionix.cn2.skullftp_gui.NetHandler;
import ose.bionix.cn2.skullftp_gui.FileHandler;
import ose.bionix.cn2.skullftp_gui.FileList;
import java.util.List;

/**
 * THIS FILE IS PARTIALLY AUTO-GENERATED BY APACHE NETBEANS IDE.
 * Alongside my primary IDE for this project, VSCode (with AI features turned off), I also used
 * NetBeans' Form Editor to quickly formulate the interface by dragging and dropping elements,
 * since manually positioning every element for it would be a massive chore.
 * The Form Editor (WHICH IS NOT AN AI) generate these codes on the fly as you make changes to
 * the form, and it expects them to not be modified AT ALL, or the editor will simply stop
 * functioning the next time you open the file.
 * As such, I did not change any bits of it throughout the development process, and therefore
 * when grading, you can skip the section that I have marked as generated by the IDE.
 * 
 * Thank you for understanding.
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    private final NetHandler net = new NetHandler();
    private final FileHandler file = new FileHandler(net);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initListeners();
        setOnline(false);
    }

    private void initListeners() {
        // Connect button
        buttonConnect.addActionListener(e -> {
            String ip = fieldIP.getText().trim();
            if (ip.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter an IP address.");
                return;
            }
            new Thread(() -> {
                try {
                    net.connect(ip, 21);
                    // Show auth UI once we have connection
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        Auth UIauth = new Auth(this, net);
                        UIauth.setLocationRelativeTo(this); // Center it over the current form
                        UIauth.setVisible(true);
                    });
                } catch (Exception ex) {
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
                    });
                }
            }).start();
        });
        // Disconnect button
        buttonDisconnect.addActionListener(e -> {
            net.disconnect();
            setOnline(false);
            clearFileList();
        });
        // Go To & Refresh Dir buttons combo
        buttonRefresh.addActionListener(e -> updFileList());
        buttonCd.addActionListener(e -> {
            String cdir = fieldPath.getText();
            try {
                file.sendFileOp("cd", cdir);
            } catch (Exception ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to change directory: " + ex.getMessage());
                });
            }
            updFileList();
        });
    }

    public void onAuth() {
        setOnline(true);
        updFileList();
    }
    private void setOnline(boolean connected) {
        buttonConnect.setEnabled(!connected);
        fieldIP.setEnabled(!connected);
        
        buttonDisconnect.setEnabled(connected);
        buttonRefresh.setEnabled(connected);
        buttonCd.setEnabled(connected);
        buttonDownload.setEnabled(connected);
        buttonUpload.setEnabled(connected);
        buttonDelete.setEnabled(connected);
        fieldPath.setEnabled(connected);
    }
        private void updFileList() {
        new Thread(() -> { // Again to not freeze the UI while we're fetching files
            try {
                // Get current path and then get file list from it
                String cdir = file.pwd();
                List<FileList> filelist = file.ls(); 

                javax.swing.SwingUtilities.invokeLater(() -> {
                    fieldPath.setText(cdir);
                    
                    // Insert filelist as rows to the table
                    javax.swing.table.DefaultTableModel tf = (javax.swing.table.DefaultTableModel) tableFile.getModel();
                    tf.setRowCount(0); // Clear old list
                    for (FileList f : filelist) {
                        tf.addRow(new Object[]{ f.getName(), f.getSize(), f.getDate() });
                    }
                });
            } catch (Exception ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to load directory: " + ex.getMessage());
                });
            }
        }).start();
    }
    private void clearFileList() {
        javax.swing.table.DefaultTableModel tf = (javax.swing.table.DefaultTableModel) tableFile.getModel();
        tf.setRowCount(0);
    }

    // ===== BEGIN NETBEANS GENERATED CODE =====

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldIP = new javax.swing.JTextField();
        buttonConnect = new javax.swing.JButton();
        buttonDisconnect = new javax.swing.JButton();
        viewFile = new javax.swing.JScrollPane();
        tableFile = new javax.swing.JTable();
        fieldPath = new javax.swing.JTextField();
        buttonRefresh = new javax.swing.JButton();
        buttonCd = new javax.swing.JButton();
        buttonDownload = new javax.swing.JButton();
        buttonUpload = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldIP.addActionListener(this::fieldIPActionPerformed);

        buttonConnect.setText("Connect");

        buttonDisconnect.setText("Disconnect");

        tableFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Size", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFile.setColumnSelectionAllowed(true);
        tableFile.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        viewFile.setViewportView(tableFile);
        tableFile.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableFile.getColumnModel().getColumnCount() > 0) {
            tableFile.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        fieldPath.setToolTipText("");

        buttonRefresh.setText("Refresh");

        buttonCd.setText("Go to");

        buttonDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonDownload.setLabel("Download...");

        buttonUpload.setLabel("Upload...");

        buttonDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewFile)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldIP)
                            .addComponent(fieldPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(buttonCd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConnect)
                    .addComponent(buttonDisconnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRefresh)
                    .addComponent(buttonCd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDownload)
                    .addComponent(buttonUpload)
                    .addComponent(buttonDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIPActionPerformed
        
    }//GEN-LAST:event_fieldIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCd;
    private javax.swing.JButton buttonConnect;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDisconnect;
    private javax.swing.JButton buttonDownload;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonUpload;
    private javax.swing.JTextField fieldIP;
    private javax.swing.JTextField fieldPath;
    private javax.swing.JTable tableFile;
    private javax.swing.JScrollPane viewFile;
    // End of variables declaration//GEN-END:variables

    // ===== END NETBEANS GENERATED CODE =====
}
